### PR TITLE
renaming to jDrupal

### PR DESCRIPTION
**Pull request by giorgio79**
resolve namespace conflict if jDrupal is on a Drupal site
https://github.com/easystreet3/jDrupal/issues/9

### CODE REVIEW

**Comment by signalpoint** [comment]
@giorgio79 This is awesome, thank you so much! I am getting ready to release the next version of DrupalGap this week. After that, I will merge this in.

I don't want to right now because the next version already has enough "changes" that people will need to make to their app to stay working, so I don't want to anger everybody ;)

**Comment by signalpoint** [comment]
@giorgio79 Sorry, I just noticed these changes all went into the `bin/` directory, when they needed to go into the various files in the `src/` directory: https://github.com/giorgio79/jDrupal/tree/7.x-1.x/src

**Comment by jacobembree** [comment]
@signalpoint Are you still interested in having this done?  It doesn't look like it would be very hard.  Would it be anything more than a careful search and replace in the `src/` folder?

**Comment by signalpoint** [comment]
@jacobembree Yes I am definitely still interested in this one. I gave it a try on a sandbox one time and it worked fine, but I hadn't tried it alongside DrupalGap. But I think it'd be easy enough to add a fail safe in DrupalGap, to set `Drupal = jDrupal;` and the problem should be solved. I'd like to see it gracefully warn DrupalGap (and DrupalGap developers far and wide) that we're replacing that. In hindsight, I sure which I didn't name it `Drupal`, dumb move.

**Comment by jacobembree** [comment]
Now that #79 has been merged this pull request can be closed.

**Pull request closed without merging**
